# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.legacy_industry.translation.commodity_translation_parser:
        class: App\LegacyIndustry\Translation\TranslationParser
        arguments:
            $dataType: commodity
            $translationFile: '%kernel.project_dir%/config/legacy_industry_cleaner/commodity_translation.yaml'

    app.legacy_industry.translation.era_translation_parser:
        class: App\LegacyIndustry\Translation\TranslationParser
        arguments:
            $dataType: era
            $translationFile: '%kernel.project_dir%/config/legacy_industry_cleaner/era_translation.yaml'

    app.legacy_industry.translation.state_translation_parser:
        class: App\LegacyIndustry\Translation\TranslationParser
        arguments:
            $dataType: state
            $translationFile: '%kernel.project_dir%/config/legacy_industry_cleaner/state_translation.yaml'

    App\LegacyIndustry\Loader\Loader:
        arguments:
            $directory: '%kernel.project_dir%/var/data'
            $files:
                - ['opsig/OpSigEST.txt', 'OpSig / EST']
                - ['opsig/OpSigMWC.txt', 'OpSig / MWC']
                - ['opsig/OpSigSTH.txt', 'OpSig / STH']
#                - ['opsig/OpSigWST.txt', 'OpSig / WST']
                - ['opsig/OpSigWEST.txt', 'OpSig / West']
                - ['opsig/OpSigCANADA.txt', 'OpSig / Canada']
                - ['keystone_crossings/OpSig_baltimoreeastern1945_170906.txt', 'Keystone Crossings / Baltimore & Eastern R. R.']
                - ['keystone_crossings/OpSig_cnj1945_170906.txt', 'Keystone Crossings / Central Railroad of New Jersey']
                - ['keystone_crossings/OpSig_hbtm1942_170802.txt', 'Keystone Crossings / Huntingdon & Broad Top Mountain Railroad']
                - ['keystone_crossings/OpSig_nylb1945_170906.txt', 'Keystone Crossings / New York & Long Branch R. R.']
                - ['keystone_crossings/OpSig_prratlantic1945_171120.txt', 'Keystone Crossings / Pennsylvania Railroad Atlantic Division']
                - ['keystone_crossings/OpSig_prrdelmarva1945_171004.txt', 'Keystone Crossings / Pennsylvania Railroad Delmarva Division']
                - ['keystone_crossings/OpSig_prrmaryland1945_170906.txt', 'Keystone Crossings / Pennsylvania Railroad Maryland Division']
                - ['keystone_crossings/OpSig_prrmiddle1945_170802.txt', 'Keystone Crossings / Pennsylvania Railroad Middle Division']
                - ['keystone_crossings/OpSig_prrnewyork1945_171004.txt', 'Keystone Crossings / Pennsylvania Railroad New York Division']
                - ['keystone_crossings/OpSig_prrphiladelphia1945_170807.txt', 'Keystone Crossings / Pennsylvania Railroad Philadelphia Division']
                - ['keystone_crossings/OpSig_prrphilaterm1945_171116.txt', 'Keystone Crossings / Pennsylvania Railroad Philadelphia Terminal Division']
                - ['keystone_crossings/OpSig_prrpittsburgh1945_170807.txt', 'Keystone Crossings / Pennsylvania Railroad Pittsburgh Division']
                - ['keystone_crossings/OpSig_prrwilkesbarre1945_170807.txt', 'Keystone Crossings / Pennsylvania Railroad Wilkes-Barre Division']
                - ['keystone_crossings/OpSig_prrwilliamsport1945_170807.txt', 'Keystone Crossings / Pennsylvania Railroad Williamsport Division']

    App\LegacyIndustry\Cleaner\CommodityCleaner:
        arguments:
            $translationParser: '@app.legacy_industry.translation.commodity_translation_parser'
        tags:
            - { name: monolog.logger, channel: legacy_industry_cleaner }

    App\LegacyIndustry\Cleaner\EraCleaner:
        arguments:
            $translationParser: '@app.legacy_industry.translation.era_translation_parser'
        tags:
            - { name: monolog.logger, channel: legacy_industry_cleaner }

    App\LegacyIndustry\Cleaner\StateCleaner:
        arguments:
            $translationParser: '@app.legacy_industry.translation.state_translation_parser'
        tags:
            - { name: monolog.logger, channel: legacy_industry_cleaner }

    App\Paperwork\Creator\FullWaybillFormCreator:
        arguments:
            $fieldData:
                - { id: formHeader, type: formHeader, position: origin, width: 1, height: 1 }
                - { id: carInitial, type: header, position: bottom, reference: formHeader, width: '@=1/4', height: '@=1/2' }
                - { id: carInitialData, type: data, position: right, reference: carInitial,  width: '@=1/4', height: '@=1/2' }
                - { id: carNumber, type: header, position: right, reference: carInitialData, width: '@=1/4', height: '@=1/2' }
                - { id: carNumberData, type: data, position: right, reference: carNumber, width: '@=1/4', height: '@=1/2'}
                - { id: aar, type: header, position: bottom, reference: carInitial, width: '@=1/4', height: '@=1/2' }
                - { id: aarData, type: data, position: right, reference: aar,  width: '@=1/4', height: '@=1/2' }
                - { id: len, type: header, position: right, reference: aarData, width: '@=1/4', height: '@=1/2' }
                - { id: lenData, type: data, position: right, reference: len, width: '@=1/4', height: '@=1/2'}
                - { id: marginLeft, type: data, position: bottom, reference: aar, width: '@=1/2', height: '@=1/6'}
                - { id: marginRight, type: data, position: right, reference: marginLeft, width: '@=1/2', height: '@=1/6'}
                - { id: stopThisCarAt, type: header, position: bottom, reference: marginLeft, width: '@=1/4', height: '@=1/3' }
                - { id: stopThisCarAtData, type: data, position: right, reference: stopThisCarAt,  width: '@=1/4', height: '@=1/3' }
                - { id: stopThisCarAt2, type: header, position: bottom, reference: stopThisCarAt, width: '@=1/4', height: '@=1/3' }
                - { id: stopThisCarAt2Data, type: data, position: right, reference: stopThisCarAt2, width: '@=1/4', height: '@=1/3'}
                - { id: waybillDate, type: header, position: right, reference: stopThisCarAtData, width: '@=3/16', height: '@=1/3' }
                - { id: waybillDateData, type: data, position: right, reference: waybillDate,  width: '@=5/16', height: '@=1/3' }
                - { id: waybillNumber, type: header, position: bottom, reference: waybillDate, width: '@=3/16', height: '@=1/3' }
                - { id: waybillNumberData, type: data, position: right, reference: waybillNumber, width: '@=5/16', height: '@=1/3'}
                - { id: to, type: header, position: bottom, reference: stopThisCarAt2, width: '@=1/2', height: '@=1/6' }
                - { id: toData, type: data, position: bottom, reference: to,  width: '@=1/2', height: '@=5/6' }
                - { id: from, type: header, position: right, reference: to, width: '@=1/2', height: '@=1/6' }
                - { id: fromData, type: data, position: bottom, reference: from, width: '@=1/2', height: '@=5/6'}
                - { id: consignee, type: header, position: bottom, reference: toData, width: '@=1/2', height: '@=1/6' }
                - { id: consigneeData, type: data, position: bottom, reference: consignee,  width: '@=1/2', height: '@=5/6' }
                - { id: shipper, type: header, position: right, reference: consignee, width: '@=1/2', height: '@=1/6' }
                - { id: shipperData, type: data, position: bottom, reference: shipper, width: '@=1/2', height: '@=5/6'}
                - { id: routeVia, type: header, position: bottom, reference: consigneeData, width: '@=1/4', height: '@=1/2' }
                - { id: routeViaData, type: data, position: right, reference: routeVia,  width: '@=3/4', height: '@=1/2' }
                - { id: instructionsAndExceptions, type: header, position: bottom, reference: routeVia, width: '@=1/3', height: '@=1/3' }
                - { id: instructionsAndExceptionsData, type: data, position: right, reference: instructionsAndExceptions,  width: '@=2/3', height: '@=1/3' }
                - { id: pkgs, type: header, position: bottom, reference: instructionsAndExceptions, width: '@=1/4', height: '@=1/6' }
                - { id: pkgsData, type: data, position: bottom, reference: pkgs,  width: '@=1/4', height: '@=5/6' }
                - { id: description, type: header, position: right, reference: pkgs, width: '@=3/4', height: '@=1/6' }
                - { id: descriptionData, type: data, position: right, reference: pkgsData, width: '@=3/4', height: '@=7/6'}
            $lines:
                - { type: horizontal, position: bottom, reference: carInitial }
                - { type: horizontal, position: bottom, reference: carInitialData }
                - { type: horizontal, position: bottom, reference: carNumber }
                - { type: horizontal, position: bottom, reference: carNumberData }
                - { type: horizontal, position: bottom, reference: consigneeData }
                - { type: horizontal, position: bottom, reference: formHeader }
                - { type: horizontal, position: bottom, reference: fromData }
                - { type: horizontal, position: bottom, reference: instructionsAndExceptions }
                - { type: horizontal, position: bottom, reference: instructionsAndExceptionsData }
                - { type: horizontal, position: bottom, reference: marginLeft }
                - { type: horizontal, position: bottom, reference: marginRight }
                - { type: horizontal, position: bottom, reference: routeVia }
                - { type: horizontal, position: bottom, reference: routeViaData }
                - { type: horizontal, position: bottom, reference: shipperData }
                - { type: horizontal, position: bottom, reference: stopThisCarAt2 }
                - { type: horizontal, position: bottom, reference: stopThisCarAt2Data }
                - { type: horizontal, position: bottom, reference: toData }
                - { type: horizontal, position: bottom, reference: waybillDate }
                - { type: horizontal, position: bottom, reference: waybillDateData }
                - { type: horizontal, position: bottom, reference: waybillNumber }
                - { type: horizontal, position: bottom, reference: waybillNumberData }
                - { type: vertical, position: right, reference: aarData }
                - { type: vertical, position: right, reference: carInitialData }
                - { type: vertical, position: right, reference: consignee }
                - { type: vertical, position: right, reference: consigneeData }
                - { type: vertical, position: right, reference: marginLeft }
                - { type: vertical, position: right, reference: stopThisCarAt2Data }
                - { type: vertical, position: right, reference: stopThisCarAtData }
                - { type: vertical, position: right, reference: to }
                - { type: vertical, position: right, reference: toData }
            $headerLabels:
                formHeader: 'Freight Waybill'
                carInitial: 'Car Initial'
                carNumber: 'Car Number'
                aar: 'AAR Class of Car Ordered'
                len: 'Length/Capy of Car Ordered'
                stopThisCarAt: 'Stop This Car At'
                stopThisCarAt2: 'At'
                waybillDate: 'Waybill Date'
                waybillNumber: 'Waybill Number'
                to: 'To Station State'
                from: 'From Station State'
                consignee: 'Consignee & Address'
                shipper: 'Shipper'
                routeVia: 'Route/Via'
                instructionsAndExceptions: 'Instructions & Exceptions'
                pkgs: '# Pkgs'
                description: 'Description of Articles'

    App\Paperwork\Creator\ShortWaybillFormCreator:
        arguments:
            $fieldData:
                - { id: marginLeft, type: data, position: origin, width: '@=1/2', height: '@=1/6'}
                - { id: marginRight, type: data, position: right, reference: marginLeft, width: '@=1/2', height: '@=1/6'}
                - { id: stopThisCarAt, type: header, position: bottom, reference: marginLeft, width: '@=1/4', height: '@=1/3' }
                - { id: stopThisCarAtData, type: data, position: right, reference: stopThisCarAt,  width: '@=1/4', height: '@=1/3' }
                - { id: stopThisCarAt2, type: header, position: bottom, reference: stopThisCarAt, width: '@=1/4', height: '@=1/3' }
                - { id: stopThisCarAt2Data, type: data, position: right, reference: stopThisCarAt2, width: '@=1/4', height: '@=1/3'}
                - { id: waybillDate, type: header, position: right, reference: stopThisCarAtData, width: '@=3/16', height: '@=1/3' }
                - { id: waybillDateData, type: data, position: right, reference: waybillDate,  width: '@=5/16', height: '@=1/3' }
                - { id: waybillNumber, type: header, position: bottom, reference: waybillDate, width: '@=3/16', height: '@=1/3' }
                - { id: waybillNumberData, type: data, position: right, reference: waybillNumber, width: '@=5/16', height: '@=1/3'}
                - { id: to, type: header, position: bottom, reference: stopThisCarAt2, width: '@=1/2', height: '@=1/6' }
                - { id: toData, type: data, position: bottom, reference: to,  width: '@=1/2', height: '@=5/6' }
                - { id: from, type: header, position: right, reference: to, width: '@=1/2', height: '@=1/6' }
                - { id: fromData, type: data, position: bottom, reference: from, width: '@=1/2', height: '@=5/6'}
                - { id: consignee, type: header, position: bottom, reference: toData, width: '@=1/2', height: '@=1/6' }
                - { id: consigneeData, type: data, position: bottom, reference: consignee,  width: '@=1/2', height: '@=5/6' }
                - { id: shipper, type: header, position: right, reference: consignee, width: '@=1/2', height: '@=1/6' }
                - { id: shipperData, type: data, position: bottom, reference: shipper, width: '@=1/2', height: '@=5/6'}
                - { id: routeVia, type: header, position: bottom, reference: consigneeData, width: '@=1/4', height: '@=1/2' }
                - { id: routeViaData, type: data, position: right, reference: routeVia,  width: '@=3/4', height: '@=1/2' }
                - { id: instructionsAndExceptions, type: header, position: bottom, reference: routeVia, width: '@=1/3', height: '@=1/3' }
                - { id: instructionsAndExceptionsData, type: data, position: right, reference: instructionsAndExceptions,  width: '@=2/3', height: '@=1/3' }
                - { id: pkgs, type: header, position: bottom, reference: instructionsAndExceptions, width: '@=1/4', height: '@=1/6' }
                - { id: pkgsData, type: data, position: bottom, reference: pkgs,  width: '@=1/4', height: '@=5/6' }
                - { id: description, type: header, position: right, reference: pkgs, width: '@=3/4', height: '@=1/6' }
                - { id: descriptionData, type: data, position: right, reference: pkgsData, width: '@=3/4', height: '@=7/6'}
            $lines:
                - { type: horizontal, position: bottom, reference: consigneeData }
                - { type: horizontal, position: bottom, reference: fromData }
                - { type: horizontal, position: bottom, reference: instructionsAndExceptions }
                - { type: horizontal, position: bottom, reference: instructionsAndExceptionsData }
                - { type: horizontal, position: bottom, reference: routeVia }
                - { type: horizontal, position: bottom, reference: routeViaData }
                - { type: horizontal, position: bottom, reference: shipperData }
                - { type: horizontal, position: bottom, reference: stopThisCarAt2 }
                - { type: horizontal, position: bottom, reference: stopThisCarAt2Data }
                - { type: horizontal, position: bottom, reference: toData }
                - { type: horizontal, position: bottom, reference: waybillDate }
                - { type: horizontal, position: bottom, reference: waybillDateData }
                - { type: horizontal, position: bottom, reference: waybillNumber }
                - { type: horizontal, position: bottom, reference: waybillNumberData }
                - { type: vertical, position: right, reference: consignee }
                - { type: vertical, position: right, reference: consigneeData }
                - { type: vertical, position: right, reference: stopThisCarAt2Data }
                - { type: vertical, position: right, reference: stopThisCarAtData }
                - { type: vertical, position: right, reference: to }
                - { type: vertical, position: right, reference: toData }
            $headerLabels:
                stopThisCarAt: 'Stop This Car At'
                stopThisCarAt2: 'At'
                waybillDate: 'Waybill Date'
                waybillNumber: 'Waybill Number'
                to: 'To Station State'
                from: 'From Station State'
                consignee: 'Consignee & Address'
                shipper: 'Shipper'
                routeVia: 'Route/Via'
                instructionsAndExceptions: 'Instructions & Exceptions'
                pkgs: '# Pkgs'
                description: 'Description of Articles'

    Faker\Generator:
        factory: ['Faker\Factory', create]