- ['#cottonseed oil mill']
- ['#feed mill']
- ['#fishery']
- ['#grain & feed dealer']
- ['#livestock dealer']
- ['#machinery dealer']
- ['#peanut shelling plant']
- ['abrasives']
- ['accessories']
- ['acetylene']
- ['aggregates']
- ['aluminum ingots']
- ['anhydrous ammonia']
- ['anthracite coal', 'coal, anthracite']
- ['anthracite', 'coal, anthracite']
- ['antifreeze']
- ['apples']
- ['appliances']
- ['asbestos products']
- ['ash']
- ['asphalt']
- ['auto accessories plt', '#auto accessories plant']
- ['auto dlr', '#automobile dealer']
- ['auto parts']
- ['auto plt', '#automobile plant']
- ['auto supplies', 'automobile supplies']
- ['automobiles']
- ['autos & vehicles', ['automobiles', 'vehicles']]
- ['autos', 'automobiles']
- ['axes']
- ['bad order cars']
- ['bags']
- ['bakery goods', 'bakery goods']
- ['bakery', '#bakery']
- ['bananas']
- ['barley']
- ['barley, wheat', ['barley', 'wheat']]
- ['basket factory', '#basket factory']
- ['batteries']
- ['beans']
- ['bed plates']
- ['beer distr', '#beer distributor']
- ['beer distributor', '#beer distributor']
- ['beer']
- ['bentonite']
- ['benzol']
- ['benzol, coke byprod, copper prods', ['benzol', 'coke byproducts', 'copper products']]
- ['beverages']
- ['biscuits']
- ['bldg materials', 'building materials']
- ['bldg matls', 'building materials']
- ['bldg supplies', 'building supplies']
- ['bldrs supp', 'builders supplies']
- ['bolts etc', 'bolts']
- ['borax']
- ['bottles']
- ['bottling plt', '#bottling plant']
- ['bottling supplies']
- ['boxes']
- ['brewery', '#brewery']
- ['brick etc', 'bricks']
- ['brick']
- ['bricks', 'brick']
- ['bridges']
- ['builders supplies']
- ['building material', 'building materials']
- ['building materials']
- ['building supplies']
- ['bulk gas & oil', ['bulk gas', 'bulk oil']]
- ['bulk gas']
- ['bulk oil']
- ['buses']
- ['butter']
- ['cabinets']
- ['candy']
- ['canned goods']
- ['canned vegetables']
- ['cannery', '#cannery']
- ['canning plt', '#canning plant']
- ['cans etc', 'cans']
- ['cans']
- ['carbon black']
- ['cardboard packaging']
- ['cardboard']
- ['caskets']
- ['cast iron fittings']
- ['cast iron pipe & fittings', ['cast iron pipe', 'cast iron fittings']]
- ['cast iron pipe & fittings, bed plates', ['cast iron pipe', 'cast iron fittings', 'bed plates']]
- ['cast iron pipe']
- ['cast iron valves']
- ['castings']
- ['cattle']
- ['cd gds', 'canned goods']
- ['cement block plt', '#cement block plant']
- ['cement blocks']
- ['cement']
- ['cement, aggregates', ['cement', 'aggregates']]
- ['cereal']
- ['cereals']
- ['charcoal']
- ['cheese']
- ['chem plt', '#chemical plant']
- ['chem', 'chemicals']
- ['chemicals']
- ['chems', 'chemicals']
- ['chlorine']
- ['cinders']
- ['citrus']
- ['clay']
- ['clothing products']
- ['clothing']
- ['coal & lbr yd', '#coal & lumber dealer']
- ['coal tons/day', 'coal']
- ['coal yd', '#coal yard']
- ['coal']
- ['coal, anthracite']
- ['coal, bituminous']
- ['coal, bldrs supp', ['coal', 'builders supplies']]
- ['coal, coke, sugar beets', ['coal', 'coke', 'sugar beets']]
- ['coal, feed', ['coal', 'feed']]
- ['coal, freight - all kinds', ['coal', 'freight - all kinds']]
- ['coal, ice', ['coal', 'ice']]
- ['coal, lb', ['coal', 'lumber']]
- ['coal, lumber', ['coal', 'lumber']]
- ['coal, metallurgical']
- ['coal, petr prod', ['coal', 'petroleum products']]
- ['coal, petroleum products', ['coal', 'petroleum products']]
- ['coal, pulpwood', ['coal', 'pulpwood']]
- ['coal, steam', 'coal, bituminous']
- ['coffee']
- ['coke byproducts']
- ['coke etc', 'coke']
- ['coke']
- ['cold storage', '#cold storage']
- ['compressed gases']
- ['concrete blocks']
- ['concrete pipe']
- ['concrete products']
- ['containers']
- ['contractor', '#contractor']
- ['contractors', '#contractors']
- ['cooperage']
- ['copper concentrate']
- ['copper products']
- ['corn syrup']
- ['corn']
- ['cotton broker/dealer', '#cotton broker / dealer']
- ['cotton compress/whse', 'cotton compress']
- ['cotton mill', '#cotton mill']
- ['cotton spinning/weaving', '#cotton spinning/weaving']
- ['cotton']
- ['cottonseed oil mill', '#cottonseed oil mill']
- ['cottonseed oil mill, peanut shelling plt', ['#cottonseed oil mill', '#peanut shelling plant']]
- ['cottonseed oil']
- ['creamery', '#creamery']
- ['dairy products']
- ['dairy']
- ['diatomaceous earth']
- ['diatomaceous earth, limestone', ['diatomaceous earth', 'limestone']]
- ['diesel']
- ['drugs']
- ['dry ice']
- ['elec eqt', 'electrical equipment']
- ['elec goods', 'electrical goods']
- ['electrical machinery']
- ['electrical machinery/supplies', ['electrical machinery', 'electrical supplies']]
- ['electrical supplies']
- ['elev', '#elevator']
- ['empty cans']
- ['excelsior']
- ['explosives']
- ['express']
- ['fak (freight all kinds', 'freight, all kinds']
- ['fak (freight all kinds)', 'freight, all kinds']
- ['farm eqt', 'farm equipment']
- ['farm equipment']
- ['farm implements']
- ['farm implts, fertz, seed', ['farm implements', 'fertilizer', 'seed']]
- ['farm machinery']
- ['fdy', '#foundry']
- ['feed mill', '#feed mill']
- ['feed mill, mol;asses', ['#feed mill', 'molasses']]
- ['feed']
- ['feed, fuel', ['feed', 'fuel']]
- ['feed, grain', ['feed', 'grain']]
- ['feed, seed, grain']
- ['feeds', 'feed']
- ['fencing']
- ['fertilizer & sugar mill machinery', ['fertilizer', 'sugar mill machinery']]
- ['fertilizer']
- ['fertz dlr', '#fertalizer dealer']
- ['fertz', 'fertilizer']
- ['fiberboard']
- ['fiberglass']
- ['fiberwood']
- ['fibreboard']
- ['fireworks']
- ['fish packers', '#fish packers']
- ['fish']
- ['flooring']
- ['flour mill', '#flour mill']
- ['flour']
- ['flour, feed', ['flour', 'feed']]
- ['flour, feed, seed, hay', ['flour', 'feed', 'seed', 'hay']]
- ['flour/feed', ['flour', 'feed']]
- ['flux stone']
- ['fly ash']
- ['food prod', 'food products']
- ['food products']
- ['forest products']
- ['formed roofing prods, fencing, pig iron', ['formed roofing products', 'fencing', 'pig iron']]
- ['formed roofing products']
- ['forwarder freight', '#freight forwarder']
- ['forwarders', '#freight forwarders']
- ['foundry', '#foundry']
- ['freight - all kinds', 'freight, all kinds']
- ['freight - all kinds, automobiles', ['freight - all kinds', 'automobiles']]
- ['freight cars']
- ['freight forwarder', '#freight forwarder']
- ['frozen chickens']
- ['frozen foods']
- ['frozen products']
- ['frt forwarder', '#freight forwarder']
- ['frt fwdr', '#freight forwarders']
- ['fruit']
- ['fruit/vegetables', ['fruit', 'vegetables']]
- ['fruits/vegetables', ['fruit', 'vegetables']]
- ['fuel oil']
- ['fuel']
- ['furn factory', '#furnature factory']
- ['furn', 'furniture']
- ['furnacces']
- ['furnaces']
- ['furniture']
- ['galvanized steel sheets']
- ['galvanized steel sheets, wire', ['galvanized steel sheets', 'wire']]
- ['galvanized steel work', '#galvanized steel work']
- ['garage doors']
- ['gasoline']
- ['general merchandise']
- ['glass']
- ['glassware']
- ['grain elevator', '#grain elevator']
- ['grain']
- ['grain, bulk']
- ['grain, feed', ['grain', 'feed']]
- ['grain/coal', ['grain', 'coal']]
- ['grain/feed dealer', '#grain/feed dealer']
- ['grain/feed dealer, coal', ['#grain & feed dealer', 'coal']]
- ['grain/feed dealer, seed', ['seed', '#grain & feed dealer']]
- ['grain/feed dealer, whsl groc', ['#grain & feed dealer', 'wholesale groceries']]
- ['grain/feed dealer, whsl groc, fertz', ['#grain & feed dealer', 'wholesale groceries', 'fertilizer']]
- ['grain/feed', ['grain', 'feed']]
- ['grain/feed, coal', ['grain', 'feed', 'coal']]
- ['grapes']
- ['gravel']
- ['groc', 'groceries']
- ['groceries']
- ['grocery products']
- ['gypsum']
- ['hardware']
- ['hay']
- ['hdw', 'hardware']
- ['heading']
- ['hides']
- ['hoops']
- ['hops etc', 'hops']
- ['hops']
- ['ice']
- ['implements']
- ['implt dlr', '#implament dealer']
- ['insulation']
- ['interchange']
- ['iron ore']
- ['iron']
- ['junk scrap iron & metal dealer', '#junk scrap iron & metal dealer']
- ['junk']
- ['kaolin']
- ['kerosene']
- ['knitting mill', '#knitting mill']
- ['lbr yd', '#lumber yard']
- ['lbr', 'lumber']
- ['leather']
- ['lime']
- ['lime, stone', ['lime', 'stone']]
- ['limestone']
- ['liquid petroleum gas']
- ['liquified petroleum', ['liquid petroleum gas']]
- ['liquor']
- ['livestock dealer', '#livestock dealer']
- ['livestock dealer, hides', ['hides', '#livestock dealer']]
- ['livestock shipper', '#livestock shipper']
- ['livestock']
- ['locomotives']
- ['logs']
- ['lp gas', 'liquid petroleum gas']
- ['lpg', 'liquid petroleum gas']
- ['lube oil']
- ['lumber mill', '#lumber mill']
- ['lumber remanufacturing', '#lumber remanufacturing']
- ['lumber']
- ['lumber, coal', ['lumber', 'coal']]
- ['lumber, coal, petroleum products', ['lumber', 'coal', 'petroleum products']]
- ['lumber, plywood', ['lumber', 'plywood']]
- ['lumber, wood chips', ['lumber', 'wood chips']]
- ['lumber/bldg materials', ['lumber', 'building materials']]
- ['lumber/coal', ['lumber', 'coal']]
- ['machine shop', '#machine shop']
- ['machinery dealer', '#machinery dealer']
- ['machinery dlr, farm implts', ['#machinery dealer', 'farm implements']]
- ['machinery']
- ['machy', 'machinery']
- ['mail & express', ['mail', 'express']]
- ['mail']
- ['malt']
- ['marble (quarry)', 'marble']
- ['marble']
- ['matches']
- ['mattresses']
- ['mdse', 'merchandise']
- ['meat prod (slaughterhouse)', 'meat products']
- ['meat prod', 'meat']
- ['meat']
- ['meats', 'meat']
- ['merchandise']
- ['metal utility cabinets']
- ['metal utility cabinets, radiator covers', ['metal utility cabinets', 'radiator covers']]
- ['metals']
- ['mfr brick', 'brick']
- ['mfr high grade manganese ore', 'high grade manganese ore']
- ['mfr ice', 'ice']
- ['mfr phosphate rock, chem', ['phosphate rock', 'chemicals']]
- ['mfr soap', ['soap']]
- ['mfr staves/hoops/heading, cooperage', ['staves', 'hoops', 'heading', 'cooperage']]
- ['milk']
- ['millwork']
- ['mixed foods']
- ['molasses']
- ['motor veh parts & acc', ['motor vehicle parts', 'motor vehicle accessories']]
- ['motor veh supp & parts', '#motor vehicle supplies and parts']
- ['motor vehicle accessories']
- ['motor vehicle parts']
- ['napthalene']
- ['napthalene, solvent naptha, tar, toluol', ['napthalene', 'petroleum naphtha', 'tar', 'toluene']]
- ['naval stores broker', '#naval stores broker']
- ['naval stores distillation plant', '#naval stores distillation plant']
- ['newspaper']
- ['newsprint']
- ['oats']
- ['oil & gasoline', ['oil', 'gasoline']]
- ['oil well supply house', '#oil well supply house']
- ['oil']
- ['oil, diesel, kerosene, gasoline', ['oil', 'diesel', 'kerosene', 'gasoline']]
- ['oil, kerosene, gasoline, diesel', ['oil', 'kerosene', 'gasoline', 'diesel']]
- ['oranges']
- ['packing house products']
- ['packing house', '#packing house']
- ['paint']
- ['paint/oil/varnish, plbg supp', ['paint', 'oil', 'varnish', 'plumbing supplies']]
- ['paints', 'paint']
- ['pallets']
- ['paper bags']
- ['paper boxes']
- ['paper prod', 'paper products']
- ['paper prods plt', '#paper products plant']
- ['paper products']
- ['paper waste']
- ['paper']
- ['particle board']
- ['parts & accessories', ['parts', 'accessories']]
- ['parts']
- ['perlite']
- ['petr coke', 'petroleum coke']
- ['petr prod', 'petroleum products']
- ['petroleum naphtha']
- ['petroleum products']
- ['petroleum products.', 'petroleum products']
- ['petroleum']
- ['phosphate rock']
- ['phosphate']
- ['phosphoric acid']
- ['pickle sta', 'pickles']
- ['pies, fz', 'frozen pies']
- ['pig iron']
- ['pigments']
- ['piling']
- ['pipe']
- ['planing mill', '#planing mill']
- ['plastic pellets']
- ['plastic']
- ['plastics']
- ['plumbing supplies']
- ['plywood']
- ['poles & piling', ['poles', 'piling']]
- ['poles']
- ['potash']
- ['potato whse', '#potato wholesaler']
- ['potatoes']
- ['poultry']
- ['printing paper']
- ['produce dlr', '#produce dealer']
- ['produce']
- ['propane gas', 'propane']
- ['propane']
- ['public warehouse', '#public warehouse']
- ['pulpboard']
- ['pulpwood shipper', '#pulpwood shipper']
- ['pulpwood']
- ['pumice']
- ['radiator covers']
- ['rags']
- ['railroad products']
- ['railroad rail']
- ['railroad ties']
- ['rayon']
- ['refrigerators']
- ['resins']
- ['rice']
- ['roofing materials']
- ['roofing']
- ['rosin oil']
- ['salt mine', '#salt mine']
- ['salt']
- ['sand & gravel', ['sand', 'gravel']]
- ['sand']
- ['sand, gravel', ['sand', 'gravel']]
- ['sand/gravel', ['sand', 'gravel']]
- ['saw & planing mill', '#saw & planing mill']
- ['sawmill & planing mill', '#sawmill & planing mill']
- ['sawmill', '#sawmill']
- ['saws']
- ['scrap iron']
- ['scrap metal']
- ['scrap paper']
- ['scrap yd', '#scrap yard']
- ['scrap']
- ['screws']
- ['seed & grain', ['seed', 'grain']]
- ['seed']
- ['seeds', 'seed']
- ['sheet metal']
- ['shingles']
- ['shoes']
- ['slag']
- ['sleds']
- ['soap']
- ['soda ash']
- ['sodium chlorate']
- ['soybean meal']
- ['soybean oil']
- ['soybean oil, meal', ['soybean oil', 'soybean meal']]
- ['soybeans']
- ['staves']
- ['steel angles & channels, bars & plates', ['steel angles', 'steel channels', 'steel bars', 'steel plates']]
- ['steel angles']
- ['steel bars']
- ['steel billets']
- ['steel castings']
- ['steel channels']
- ['steel etc', 'steel']
- ['steel ingots & billets, rebars, sheet, slabs', ['steel ingots', 'steel billets', 'steel rebar', 'steel sheet', 'steel slabs']]
- ['steel ingots']
- ['steel pipe']
- ['steel plate']
- ['steel plates']
- ['steel products']
- ['steel rebar']
- ['steel sheet']
- ['steel slabs']
- ['steel']
- ['stl prod', 'steel products']
- ['stone']
- ['storage warehouse', '#storage warehouse']
- ['storage whse', '#storage warehouse']
- ['storage', '#storage']
- ['stoves']
- ['structural steel']
- ['structural steel/bridges etc', ['structural steel', 'bridges']]
- ['sugar beets']
- ['sugar mill machinery']
- ['sugar refinery', '#sugar refinery']
- ['sugar']
- ['sugar, groc', ['sugar', 'groceries']]
- ['sulfuric acid']
- ['sulphate of ammonia', 'ammonium sulfate']
- ['sulphate of iron (copperas)', 'iron sulfate']
- ['supp yd', '#supply yard']
- ['supplies']
- ['supply yd', '#supply yard']
- ['tallow']
- ['tar']
- ['textile plt', '#textile plant']
- ['textiles']
- ['tile']
- ['tires']
- ['toluene']
- ['tomato products']
- ['toys']
- ['tractors']
- ['transfer', '#transfer']
- ['transportation', '#transportation']
- ['trucks']
- ['vans']
- ['varnish']
- ['vegetables']
- ['vehicles']
- ['veneer']
- ['vinegar']
- ['wallboard']
- ['warehouse', '#warehouse']
- ['waste paper']
- ['waste rags']
- ['wheat']
- ['whiskey']
- ['whlse candy/tobacco', ['wholesale candy', 'wholesale tobacco']]
- ['whlse groc, sugar', ['wholesale groceries', 'sugar']]
- ['whlse groceries', 'wholesale groceries']
- ['whlse groceries, sugar', ['wholesale groceries', 'sugar']]
- ['whlse grocery', '#wholesale grocery']
- ['whlse hardware', 'wholesale hardware']
- ['whlse plumbing supplies', 'wholesale plumbing supplies']
- ['wholesale candy']
- ['wholesale groceries']
- ['wholesale tobacco']
- ['whse', '#wholesaler']
- ['whsl groc', '#wholesale grocery']
- ['wine']
- ['wire rope']
- ['wire']
- ['wood chips']
- ['wood products']
- ['wooden pallets', 'wooden pallets']
- ['woodpulp', 'pulpwood']
- ['wool']
- ['woolen mill', '#woolen mill']
- ['wrapping paper']
- ['zinc ingots, 41', 'zinc ingots']
